create type "public"."Status" as enum ('draft', 'active', 'deleted');

drop policy "Enable insert for users based on leader_id" on "public"."teams";

drop policy "Enable creating team only if user is not part of one" on "public"."teams";


  create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "description" text not null,
    "image" text not null,
    "status" public."Status" not null default 'draft'::public."Status",
    "user_id" uuid not null,
    "team_id" uuid not null
      );


alter table "public"."products" enable row level security;

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."products" add constraint "products_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) not valid;

alter table "public"."products" validate constraint "products_team_id_fkey";

alter table "public"."products" add constraint "products_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) not valid;

alter table "public"."products" validate constraint "products_user_id_fkey";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";


  create policy "Enable delete for team leaders"
  on "public"."products"
  as permissive
  for delete
  to authenticated
using (((team_id = public.get_team_id_for_current_user()) AND (user_id = ( SELECT t.leader_id
   FROM public.teams t
  WHERE (t.id = products.team_id)))));



  create policy "Enable insert for authenticated users only"
  on "public"."products"
  as permissive
  for insert
  to authenticated
with check (((user_id = ( SELECT auth.uid() AS uid)) AND (team_id = public.get_team_id_for_current_user())));



  create policy "Enable read access for all users"
  on "public"."products"
  as permissive
  for select
  to public
using ((status = 'active'::public."Status"));



  create policy "Enable read access if not active for team members"
  on "public"."products"
  as permissive
  for select
  to authenticated
using (((status <> 'active'::public."Status") AND (team_id = public.get_team_id_for_current_user())));



  create policy "Enable update for team members only if draft"
  on "public"."products"
  as permissive
  for update
  to authenticated
using (((team_id = public.get_team_id_for_current_user()) AND (status = 'draft'::public."Status")));



  create policy "Enable delete for users based on leader_id"
  on "public"."teams"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = leader_id));



  create policy "Enable delete for users"
  on "public"."users"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable creating team only if user is not part of one"
  on "public"."teams"
  as permissive
  for insert
  to authenticated
with check (((( SELECT auth.uid() AS uid) = leader_id) AND (public.get_team_id_for_current_user() IS NULL)));


CREATE TRIGGER handle_product_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.moddatetime('updated_at');


